services:
  - type: web
    name: music-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: MUSIC_CHANNEL_ID
        sync: false
      - key: LAVALINK_HOST
        value: lavalinkv4.serenetia.com
      - key: LAVALINK_PORT
        value: "443"
      - key: LAVALINK_PASSWORD
        value: "https://seretia.link/discord"
      - key: LAVALINK_SECURE
        value: "true"
